######################
# project properties #
######################
projectVersion=9.1-SNAPSHOT
groupPackage=io.github.astrapi69
projectSourceCompatibility=17
projectInceptionYear=2015
projectHolderUsername=astrapi69
projectLeaderName=Asterios Raptis
slash=/
colon=:
issuesPath=/issues
projectDescription=Provides several swing components and utilities
projectScmProviderDomain=github.com
projectScmProviderUrl=https://github.com/
projectScmGitUrlPrefix=scm:git:git:@
projectScmGitUrlSuffix=.git
projectLicenseName=MIT License
projectLicenseUrl=https://www.opensource.org/licenses/mit-license.php
projectOrganizationName=Asterios Raptis
projectOrganizationUrl=https://astrapi69.github.io/
projectLicenseDistribution=repo
projectIssueManagementSystem=GitHub
projectRepositoriesReleasesRepoUrl=https://oss.sonatype.org/service/local/staging/deploy/maven2/
projectRepositoriesSnapshotsRepoUrl=https://oss.sonatype.org/content/repositories/snapshots
projectRepositoriesUserNameKey=ossrhUsername
projectRepositoriesPasswordKey=ossrhPassword
projectRepositoriesReleasesName=Sonatype Nexus Releases
projectRepositoriesSnapshotsName=Sonatype Nexus Snapshots
projectRepositoriesMavenUrl=https://plugins.gradle.org/m2/
##########################
# for deploy on sonatype #
##########################
systemProp.org.gradle.internal.publish.checksums.insecure=true
#############################
# gradle related properties #
#############################
# Enable the Gradle daemon
org.gradle.daemon=true
# Enable the build cache
org.gradle.caching=true
# Enable parallel execution
org.gradle.parallel=true
# Run Gradle in offline mode
org.gradle.offline=false
# Configure console output
org.gradle.console=auto
# Set the warning mode
org.gradle.warning.mode=summary
# Enable Configure on Demand to improve configuration time
org.gradle.configureondemand=true
# Enable VFS watching for better performance
org.gradle.vfs.watch=true
