dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    implementation libs.javahelp
    implementation libs.swingx.all
    implementation libs.imgscalr.lib
    implementation libs.batik.transcoder
    implementation libs.batik.codec
    implementation libs.itextpdf
    implementation libs.miglayout.swing
    implementation libs.commons.lang3
    implementation libs.silly.collection
    implementation libs.silly.bean
    implementation libs.randomizer
    implementation libs.state
    implementation libs.observer
    implementation libs.model.data
    implementation libs.jobj.core
    implementation libs.throwable
    implementation libs.silly.math
    implementation libs.menu.action
    implementation libs.swing.base.components
    implementation libs.icon.img.extensions
    implementation libs.swing.renderer
    implementation libs.component.model
    implementation libs.swing.model.components

    testImplementation libs.awt.extensions
    testImplementation libs.silly.io
    testImplementation libs.beansbinding
    testImplementation libs.crypt.api
    testImplementation libs.file.worker
    testImplementation libs.test.objects
    testImplementation libs.tango.icon.theme
    testImplementation libs.silk.icon.theme
    testImplementation libs.zip4j
    testImplementation libs.assertj.swing
    testImplementation libs.meanbean
    testImplementation libs.junit.jupiter.extensions
    // Note: use of bundles...
    testImplementation libs.bundles.unit.testing
    testRuntimeOnly libs.junit.platform.launcher
}
